// <auto-generated />
using System;
using AchParser.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AchParser.Api.Data.Migrations
{
    [DbContext(typeof(AchParserDbContext))]
    partial class AchParserDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AchParser.Api.Models.AchFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("filename");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash");

                    b.Property<string>("UnparsedFile")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unparsed_file");

                    b.HasKey("Id")
                        .HasName("pk_ach_files");

                    b.HasIndex("Hash")
                        .IsUnique()
                        .HasDatabaseName("ix_ach_files_hash");

                    b.ToTable("ach_files", (string)null);
                });

            modelBuilder.Entity("AchParser.Api.Models.Addenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EntryDetailId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_detail_id");

                    b.Property<string>("Information")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("information");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("line_number");

                    b.Property<string>("UnparsedRecord")
                        .IsRequired()
                        .HasColumnType("char(94)")
                        .HasColumnName("unparsed_record");

                    b.HasKey("Id")
                        .HasName("pk_addendas");

                    b.HasIndex("EntryDetailId")
                        .HasDatabaseName("ix_addendas_entry_detail_id");

                    b.ToTable("addendas", (string)null);
                });

            modelBuilder.Entity("AchParser.Api.Models.BatchControl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchHeaderId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_header_id");

                    b.Property<int>("EntryAddendaCount")
                        .HasColumnType("integer")
                        .HasColumnName("entry_addenda_count");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("line_number");

                    b.Property<decimal>("TotalCredit")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_credit");

                    b.Property<decimal>("TotalDebit")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_debit");

                    b.Property<string>("UnparsedRecord")
                        .IsRequired()
                        .HasColumnType("char(94)")
                        .HasColumnName("unparsed_record");

                    b.HasKey("Id")
                        .HasName("pk_batch_controls");

                    b.HasIndex("BatchHeaderId")
                        .IsUnique()
                        .HasDatabaseName("ix_batch_controls_batch_header_id");

                    b.ToTable("batch_controls", (string)null);
                });

            modelBuilder.Entity("AchParser.Api.Models.BatchHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AchFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("ach_file_id");

                    b.Property<string>("CompanyIdentification")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_identification");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_name");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("line_number");

                    b.Property<string>("ServiceClassCode")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("service_class_code");

                    b.Property<string>("UnparsedRecord")
                        .IsRequired()
                        .HasColumnType("char(94)")
                        .HasColumnName("unparsed_record");

                    b.HasKey("Id")
                        .HasName("pk_batch_headers");

                    b.HasIndex("AchFileId")
                        .HasDatabaseName("ix_batch_headers_ach_file_id");

                    b.ToTable("batch_headers", (string)null);
                });

            modelBuilder.Entity("AchParser.Api.Models.EntryDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_number");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("BatchHeaderId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_header_id");

                    b.Property<string>("IndividualName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("individual_name");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("line_number");

                    b.Property<string>("RoutingNumber")
                        .IsRequired()
                        .HasColumnType("char(9)")
                        .HasColumnName("routing_number");

                    b.Property<string>("UnparsedRecord")
                        .IsRequired()
                        .HasColumnType("char(94)")
                        .HasColumnName("unparsed_record");

                    b.HasKey("Id")
                        .HasName("pk_entry_details");

                    b.HasIndex("BatchHeaderId")
                        .HasDatabaseName("ix_entry_details_batch_header_id");

                    b.ToTable("entry_details", (string)null);
                });

            modelBuilder.Entity("AchParser.Api.Models.FileControl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AchFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("ach_file_id");

                    b.Property<int>("BatchCount")
                        .HasColumnType("integer")
                        .HasColumnName("batch_count");

                    b.Property<int>("BlockCount")
                        .HasColumnType("integer")
                        .HasColumnName("block_count");

                    b.Property<int>("EntryAddendaCount")
                        .HasColumnType("integer")
                        .HasColumnName("entry_addenda_count");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("line_number");

                    b.Property<decimal>("TotalCredit")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_credit");

                    b.Property<decimal>("TotalDebit")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_debit");

                    b.Property<string>("UnparsedRecord")
                        .IsRequired()
                        .HasColumnType("char(94)")
                        .HasColumnName("unparsed_record");

                    b.HasKey("Id")
                        .HasName("pk_file_controls");

                    b.HasIndex("AchFileId")
                        .IsUnique()
                        .HasDatabaseName("ix_file_controls_ach_file_id");

                    b.ToTable("file_controls", (string)null);
                });

            modelBuilder.Entity("AchParser.Api.Models.FileHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AchFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("ach_file_id");

                    b.Property<DateTime>("FileCreationDate")
                        .HasColumnType("date")
                        .HasColumnName("file_creation_date");

                    b.Property<TimeSpan>("FileCreationTime")
                        .HasColumnType("time")
                        .HasColumnName("file_creation_time");

                    b.Property<string>("ImmediateDestination")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("immediate_destination");

                    b.Property<string>("ImmediateDestinationName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("immediate_destination_name");

                    b.Property<string>("ImmediateOrigin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("immediate_origin");

                    b.Property<string>("ImmediateOriginName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("immediate_origin_name");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("line_number");

                    b.Property<string>("UnparsedRecord")
                        .IsRequired()
                        .HasColumnType("char(94)")
                        .HasColumnName("unparsed_record");

                    b.HasKey("Id")
                        .HasName("pk_file_headers");

                    b.HasIndex("AchFileId")
                        .IsUnique()
                        .HasDatabaseName("ix_file_headers_ach_file_id");

                    b.ToTable("file_headers", (string)null);
                });

            modelBuilder.Entity("AchParser.Api.Models.Addenda", b =>
                {
                    b.HasOne("AchParser.Api.Models.EntryDetail", "EntryDetail")
                        .WithMany("Addendas")
                        .HasForeignKey("EntryDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_addendas_entry_details_entry_detail_id");

                    b.Navigation("EntryDetail");
                });

            modelBuilder.Entity("AchParser.Api.Models.BatchControl", b =>
                {
                    b.HasOne("AchParser.Api.Models.BatchHeader", "BatchHeader")
                        .WithOne("BatchControl")
                        .HasForeignKey("AchParser.Api.Models.BatchControl", "BatchHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_batch_controls_batch_headers_batch_header_id");

                    b.Navigation("BatchHeader");
                });

            modelBuilder.Entity("AchParser.Api.Models.BatchHeader", b =>
                {
                    b.HasOne("AchParser.Api.Models.AchFile", "AchFile")
                        .WithMany("BatchHeaders")
                        .HasForeignKey("AchFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_batch_headers_ach_files_ach_file_id");

                    b.Navigation("AchFile");
                });

            modelBuilder.Entity("AchParser.Api.Models.EntryDetail", b =>
                {
                    b.HasOne("AchParser.Api.Models.BatchHeader", "BatchHeader")
                        .WithMany("EntryDetails")
                        .HasForeignKey("BatchHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_entry_details_batch_headers_batch_header_id");

                    b.Navigation("BatchHeader");
                });

            modelBuilder.Entity("AchParser.Api.Models.FileControl", b =>
                {
                    b.HasOne("AchParser.Api.Models.AchFile", "AchFile")
                        .WithOne("FileControl")
                        .HasForeignKey("AchParser.Api.Models.FileControl", "AchFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_file_controls_ach_files_ach_file_id");

                    b.Navigation("AchFile");
                });

            modelBuilder.Entity("AchParser.Api.Models.FileHeader", b =>
                {
                    b.HasOne("AchParser.Api.Models.AchFile", "AchFile")
                        .WithOne("FileHeader")
                        .HasForeignKey("AchParser.Api.Models.FileHeader", "AchFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_file_headers_ach_files_ach_file_id");

                    b.Navigation("AchFile");
                });

            modelBuilder.Entity("AchParser.Api.Models.AchFile", b =>
                {
                    b.Navigation("BatchHeaders");

                    b.Navigation("FileControl")
                        .IsRequired();

                    b.Navigation("FileHeader")
                        .IsRequired();
                });

            modelBuilder.Entity("AchParser.Api.Models.BatchHeader", b =>
                {
                    b.Navigation("BatchControl")
                        .IsRequired();

                    b.Navigation("EntryDetails");
                });

            modelBuilder.Entity("AchParser.Api.Models.EntryDetail", b =>
                {
                    b.Navigation("Addendas");
                });
#pragma warning restore 612, 618
        }
    }
}
