// <auto-generated />
using System;
using AchParser.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AchParser.Api.Migrations
{
    [DbContext(typeof(AchParserDbContext))]
    [Migration("20260321210459_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AchParser.Api.Models.AchFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("filename");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash");

                    b.Property<string>("UnparsedFile")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unparsed_file");

                    b.HasKey("Id")
                        .HasName("pk_ach_file");

                    b.ToTable("ach_file", (string)null);
                });

            modelBuilder.Entity("AchParser.Api.Models.Addenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("EntryDetailId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_detail_id");

                    b.Property<string>("Information")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("information");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("line_number");

                    b.Property<string>("UnparsedRecord")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unparsed_record");

                    b.HasKey("Id")
                        .HasName("pk_addenda");

                    b.HasIndex("EntryDetailId")
                        .HasDatabaseName("ix_addenda_entry_detail_id");

                    b.ToTable("addenda", (string)null);
                });

            modelBuilder.Entity("AchParser.Api.Models.BatchControl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchHeaderId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_header_id");

                    b.Property<int>("EntryAddendaCount")
                        .HasColumnType("integer")
                        .HasColumnName("entry_addenda_count");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("line_number");

                    b.Property<decimal>("TotalCredit")
                        .HasColumnType("numeric")
                        .HasColumnName("total_credit");

                    b.Property<decimal>("TotalDebit")
                        .HasColumnType("numeric")
                        .HasColumnName("total_debit");

                    b.Property<string>("UnparsedRecord")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unparsed_record");

                    b.HasKey("Id")
                        .HasName("pk_batch_control");

                    b.HasIndex("BatchHeaderId")
                        .HasDatabaseName("ix_batch_control_batch_header_id");

                    b.ToTable("batch_control", (string)null);
                });

            modelBuilder.Entity("AchParser.Api.Models.BatchHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AchFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("ach_file_id");

                    b.Property<string>("CompanyIdentification")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_identification");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_name");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("line_number");

                    b.Property<string>("ServiceClassCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_class_code");

                    b.Property<string>("UnparsedRecord")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unparsed_record");

                    b.HasKey("Id")
                        .HasName("pk_batch_header");

                    b.HasIndex("AchFileId")
                        .HasDatabaseName("ix_batch_header_ach_file_id");

                    b.ToTable("batch_header", (string)null);
                });

            modelBuilder.Entity("AchParser.Api.Models.EntryDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_number");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<Guid?>("BatchHeaderId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_header_id");

                    b.Property<string>("IndividualName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("individual_name");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("line_number");

                    b.Property<string>("RoutingNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("routing_number");

                    b.Property<string>("UnparsedRecord")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unparsed_record");

                    b.HasKey("Id")
                        .HasName("pk_entry_detail");

                    b.HasIndex("BatchHeaderId")
                        .HasDatabaseName("ix_entry_detail_batch_header_id");

                    b.ToTable("entry_detail", (string)null);
                });

            modelBuilder.Entity("AchParser.Api.Models.FileControl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AchFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("ach_file_id");

                    b.Property<int>("BatchCount")
                        .HasColumnType("integer")
                        .HasColumnName("batch_count");

                    b.Property<int>("BlockCount")
                        .HasColumnType("integer")
                        .HasColumnName("block_count");

                    b.Property<int>("EntryAddendaCount")
                        .HasColumnType("integer")
                        .HasColumnName("entry_addenda_count");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("line_number");

                    b.Property<decimal>("TotalCredit")
                        .HasColumnType("numeric")
                        .HasColumnName("total_credit");

                    b.Property<decimal>("TotalDebit")
                        .HasColumnType("numeric")
                        .HasColumnName("total_debit");

                    b.Property<string>("UnparsedRecord")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unparsed_record");

                    b.HasKey("Id")
                        .HasName("pk_file_control");

                    b.HasIndex("AchFileId")
                        .HasDatabaseName("ix_file_control_ach_file_id");

                    b.ToTable("file_control", (string)null);
                });

            modelBuilder.Entity("AchParser.Api.Models.FileHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AchFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("ach_file_id");

                    b.Property<DateTime>("FileCreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("file_creation_date");

                    b.Property<TimeSpan>("FileCreationTime")
                        .HasColumnType("interval")
                        .HasColumnName("file_creation_time");

                    b.Property<string>("ImmediateDestination")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("immediate_destination");

                    b.Property<string>("ImmediateDestinationName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("immediate_destination_name");

                    b.Property<string>("ImmediateOrigin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("immediate_origin");

                    b.Property<string>("ImmediateOriginName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("immediate_origin_name");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("line_number");

                    b.Property<string>("UnparsedRecord")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unparsed_record");

                    b.HasKey("Id")
                        .HasName("pk_file_header");

                    b.HasIndex("AchFileId")
                        .HasDatabaseName("ix_file_header_ach_file_id");

                    b.ToTable("file_header", (string)null);
                });

            modelBuilder.Entity("AchParser.Api.Models.Addenda", b =>
                {
                    b.HasOne("AchParser.Api.Models.EntryDetail", "EntryDetail")
                        .WithMany("Addendas")
                        .HasForeignKey("EntryDetailId")
                        .HasConstraintName("fk_addenda_entry_detail_entry_detail_id");

                    b.Navigation("EntryDetail");
                });

            modelBuilder.Entity("AchParser.Api.Models.BatchControl", b =>
                {
                    b.HasOne("AchParser.Api.Models.BatchHeader", "BatchHeader")
                        .WithMany("BatchControls")
                        .HasForeignKey("BatchHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_batch_control_batch_header_batch_header_id");

                    b.Navigation("BatchHeader");
                });

            modelBuilder.Entity("AchParser.Api.Models.BatchHeader", b =>
                {
                    b.HasOne("AchParser.Api.Models.AchFile", "AchFile")
                        .WithMany("BatchHeaders")
                        .HasForeignKey("AchFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_batch_header_ach_file_ach_file_id");

                    b.Navigation("AchFile");
                });

            modelBuilder.Entity("AchParser.Api.Models.EntryDetail", b =>
                {
                    b.HasOne("AchParser.Api.Models.BatchHeader", "BatchHeader")
                        .WithMany("EntryDetails")
                        .HasForeignKey("BatchHeaderId")
                        .HasConstraintName("fk_entry_detail_batch_header_batch_header_id");

                    b.Navigation("BatchHeader");
                });

            modelBuilder.Entity("AchParser.Api.Models.FileControl", b =>
                {
                    b.HasOne("AchParser.Api.Models.AchFile", "AchFile")
                        .WithMany("FileControls")
                        .HasForeignKey("AchFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_file_control_ach_file_ach_file_id");

                    b.Navigation("AchFile");
                });

            modelBuilder.Entity("AchParser.Api.Models.FileHeader", b =>
                {
                    b.HasOne("AchParser.Api.Models.AchFile", "AchFile")
                        .WithMany("FileHeaders")
                        .HasForeignKey("AchFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_file_header_ach_file_ach_file_id");

                    b.Navigation("AchFile");
                });

            modelBuilder.Entity("AchParser.Api.Models.AchFile", b =>
                {
                    b.Navigation("BatchHeaders");

                    b.Navigation("FileControls");

                    b.Navigation("FileHeaders");
                });

            modelBuilder.Entity("AchParser.Api.Models.BatchHeader", b =>
                {
                    b.Navigation("BatchControls");

                    b.Navigation("EntryDetails");
                });

            modelBuilder.Entity("AchParser.Api.Models.EntryDetail", b =>
                {
                    b.Navigation("Addendas");
                });
#pragma warning restore 612, 618
        }
    }
}
