// <auto-generated />
using System;
using AchParser.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AchParser.Api.Migrations
{
    [DbContext(typeof(AchParserDbContext))]
    [Migration("20260319032120_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AchParser.Api.Models.AchFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UnparsedFile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.ToTable("ach_files", (string)null);
                });

            modelBuilder.Entity("AchParser.Api.Models.Addenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EntryDetailId")
                        .HasColumnType("uuid");

                    b.Property<string>("Information")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<string>("UnparsedRecord")
                        .IsRequired()
                        .HasColumnType("char(94)");

                    b.HasKey("Id");

                    b.HasIndex("EntryDetailId");

                    b.ToTable("addendas", (string)null);
                });

            modelBuilder.Entity("AchParser.Api.Models.BatchControl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BatchHeaderId")
                        .HasColumnType("uuid");

                    b.Property<int>("EntryAddendaCount")
                        .HasColumnType("integer");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalCredit")
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("TotalDebit")
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("UnparsedRecord")
                        .IsRequired()
                        .HasColumnType("char(94)");

                    b.HasKey("Id");

                    b.HasIndex("BatchHeaderId")
                        .IsUnique();

                    b.ToTable("batch_controls", (string)null);
                });

            modelBuilder.Entity("AchParser.Api.Models.BatchHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AchFileId")
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyIdentification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<string>("ServiceClassCode")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.Property<string>("UnparsedRecord")
                        .IsRequired()
                        .HasColumnType("char(94)");

                    b.HasKey("Id");

                    b.HasIndex("AchFileId");

                    b.ToTable("batch_headers", (string)null);
                });

            modelBuilder.Entity("AchParser.Api.Models.EntryDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid>("BatchHeaderId")
                        .HasColumnType("uuid");

                    b.Property<string>("IndividualName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<string>("RoutingNumber")
                        .IsRequired()
                        .HasColumnType("char(9)");

                    b.Property<string>("UnparsedRecord")
                        .IsRequired()
                        .HasColumnType("char(94)");

                    b.HasKey("Id");

                    b.HasIndex("BatchHeaderId");

                    b.ToTable("entry_details", (string)null);
                });

            modelBuilder.Entity("AchParser.Api.Models.FileControl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AchFileId")
                        .HasColumnType("uuid");

                    b.Property<int>("BatchCount")
                        .HasColumnType("integer");

                    b.Property<int>("BlockCount")
                        .HasColumnType("integer");

                    b.Property<int>("EntryAddendaCount")
                        .HasColumnType("integer");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalCredit")
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("TotalDebit")
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("UnparsedRecord")
                        .IsRequired()
                        .HasColumnType("char(94)");

                    b.HasKey("Id");

                    b.HasIndex("AchFileId")
                        .IsUnique();

                    b.ToTable("file_controls", (string)null);
                });

            modelBuilder.Entity("AchParser.Api.Models.FileHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AchFileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FileCreationDate")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("FileCreationTime")
                        .HasColumnType("time");

                    b.Property<string>("ImmediateDestination")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImmediateDestinationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImmediateOrigin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImmediateOriginName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<string>("UnparsedRecord")
                        .IsRequired()
                        .HasColumnType("char(94)");

                    b.HasKey("Id");

                    b.HasIndex("AchFileId")
                        .IsUnique();

                    b.ToTable("file_headers", (string)null);
                });

            modelBuilder.Entity("AchParser.Api.Models.Addenda", b =>
                {
                    b.HasOne("AchParser.Api.Models.EntryDetail", "EntryDetail")
                        .WithMany("Addendas")
                        .HasForeignKey("EntryDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntryDetail");
                });

            modelBuilder.Entity("AchParser.Api.Models.BatchControl", b =>
                {
                    b.HasOne("AchParser.Api.Models.BatchHeader", "BatchHeader")
                        .WithOne("BatchControl")
                        .HasForeignKey("AchParser.Api.Models.BatchControl", "BatchHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BatchHeader");
                });

            modelBuilder.Entity("AchParser.Api.Models.BatchHeader", b =>
                {
                    b.HasOne("AchParser.Api.Models.AchFile", "AchFile")
                        .WithMany("BatchHeaders")
                        .HasForeignKey("AchFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AchFile");
                });

            modelBuilder.Entity("AchParser.Api.Models.EntryDetail", b =>
                {
                    b.HasOne("AchParser.Api.Models.BatchHeader", "BatchHeader")
                        .WithMany("EntryDetails")
                        .HasForeignKey("BatchHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BatchHeader");
                });

            modelBuilder.Entity("AchParser.Api.Models.FileControl", b =>
                {
                    b.HasOne("AchParser.Api.Models.AchFile", "AchFile")
                        .WithOne("FileControl")
                        .HasForeignKey("AchParser.Api.Models.FileControl", "AchFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AchFile");
                });

            modelBuilder.Entity("AchParser.Api.Models.FileHeader", b =>
                {
                    b.HasOne("AchParser.Api.Models.AchFile", "AchFile")
                        .WithOne("FileHeader")
                        .HasForeignKey("AchParser.Api.Models.FileHeader", "AchFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AchFile");
                });

            modelBuilder.Entity("AchParser.Api.Models.AchFile", b =>
                {
                    b.Navigation("BatchHeaders");

                    b.Navigation("FileControl");

                    b.Navigation("FileHeader");
                });

            modelBuilder.Entity("AchParser.Api.Models.BatchHeader", b =>
                {
                    b.Navigation("BatchControl")
                        .IsRequired();

                    b.Navigation("EntryDetails");
                });

            modelBuilder.Entity("AchParser.Api.Models.EntryDetail", b =>
                {
                    b.Navigation("Addendas");
                });
#pragma warning restore 612, 618
        }
    }
}
